# Site settings
title: "Joseph Passarelli"
email: joenormyl@gmail.com
url: https://joenormyl.github.io
description: "Portfolio and List of Projects for Josph Passarelli AKA Joe Normyl. Find me on GitHub, Kaggle, or send me a message below"
keywords: "your keywords, separated by commas"
skills: "Data Analytics - Python - R - Tableau - SQL - Design"
meta_author: Passarelli Joseph

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Joseph Passarelli
  location: Wichita, KS
  social: Find me
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  - title: kaggle
    url: https://www.kaggle.com/joenormyl
  - title: tumblr
    url: https://public.tableau.com/app/profile/joe.normyl
  - title: github
    url: https://github.com/JoeNormyl

# Postal address (add as many lines as necessary)
address:
  # - line: 3481 Melrose Place
  - line: Wichita, KS

# Credits content
credits: "Freelancer Theme by Jerome Lachaud"

# Build settings
permalink: /:title/
markdown: kramdown
# relative_permalinks: false

include:
  - pages
  - .htaccess

#for index
defaults:
  - scope:
      path: ""
      type: "home"
    values:
      permalink: ""

  # - scope:
  #     path: "pages/projects.html"
  #     type: "projects"
  #   values:
  #     layout: "projects"
  #     permalink: "/pages/"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "project_post"

  - scope:
      path: "projects.html"
    values:
      layout: "projects"
      permalink: "/projects"
